#!/usr/bin/env python

from debugger_ui import cpplize_debugger

cpplize_debugger.create_debugger_header()

Import("env")
Import("env_modules")

env_network_synchronizer = env_modules.Clone()

if "tracy_enable" in env and env["tracy_enable"] == "yes":
    env_network_synchronizer.Append(CPPDEFINES=["TRACY_ENABLE"])

# TODO ensure debugs are enabled only in debug builds.
env_network_synchronizer.Append(CPPDEFINES=["NS_DEBUG_ENABLED"])

env_network_synchronizer.Append(CPPDEFINES=["DISABLE_DEBUG_DATA_BUFFER"])

env_network_synchronizer.add_source_files(env.modules_sources, "core/**.cpp")
env_network_synchronizer.add_source_files(env.modules_sources, "godot4/**.cpp")
env_network_synchronizer.add_source_files(env.modules_sources, "*.cpp")
env_network_synchronizer.add_source_files(env.modules_sources, "tests/**.cpp")
