#!/usr/bin/env python

from debugger_ui import cpplize_debugger

cpplize_debugger.create_debugger_header()

Import("env")
Import("env_modules")

env_network_synchronizer = env_modules.Clone()

env_network_synchronizer.add_source_files(env.modules_sources, "*.cpp")
